minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeExclude:
  - '@taiyme/*'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd

overrides:
  '@typescript-eslint/typescript-estree': $@typescript-eslint/typescript-estree
  esbuild: $esbuild
  idna-uts46-hx>tr46: '-'

patchedDependencies:
  hono@4.8.4: patches/hono@4.8.4.patch
