onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd

patchedDependencies:
  hono@4.7.7: patches/hono@4.7.7.patch
  punycode.js@2.3.1: patches/punycode.js@2.3.1.patch

overrides:
  '@babel/generator': $@babel/generator
  '@babel/parser': $@babel/parser
  '@babel/traverse': $@babel/traverse
  '@babel/types': $@babel/types
  '@types/babel__generator': $@types/babel__generator
  '@types/babel__traverse': $@types/babel__traverse
  '@typescript-eslint/typescript-estree': $@typescript-eslint/typescript-estree
  'esbuild': $esbuild
