name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  pre-checkout:
    name: Pre checkout
    uses: ./.github/workflows/pre-checkout.yaml

  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    needs:
      - pre-checkout
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false
          ref: ${{ needs.pre-checkout.outputs.sha }}
          fetch-depth: 1

      - name: Set wrangler.jsonc
        env:
          WRANGLER_WORKER_NAME: ${{ secrets.WRANGLER_WORKER_NAME }}
          WRANGLER_CUSTOM_DOMAIN: ${{ secrets.WRANGLER_CUSTOM_DOMAIN }}
          WRANGLER_REDIRECT_KV_ID: ${{ secrets.WRANGLER_REDIRECT_KV_ID }}
        run: |
          cp wrangler.example.jsonc wrangler.jsonc
          sed -i "s/<YOUR_WORKER_NAME>/${WRANGLER_WORKER_NAME}/g" wrangler.jsonc
          sed -i "s/<YOUR_CUSTOM_DOMAIN>/${WRANGLER_CUSTOM_DOMAIN}/g" wrangler.jsonc
          sed -i "s/<YOUR_REDIRECT_KV_ID>/${WRANGLER_REDIRECT_KV_ID}/g" wrangler.jsonc

      - name: Set environment variables
        env:
          VITE_SITE_URL: ${{ secrets.VITE_SITE_URL }}
        run: |
          touch .env.production
          echo "VITE_SITE_URL=${VITE_SITE_URL}" >> .env.production

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm run build

      - name: Deploy to Cloudflare Worker
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
